services:
  Invertus\dpdBaltics\Presenter\DeliveryTimePresenter:
    arguments:
      - '@context'
      - '@dpdbaltics'

  Invertus\dpdBaltics\Presenter\SameDayDeliveryMessagePresenter:
    arguments:
      - '@context'
      - '@dpdbaltics'